spring:
  application:
    name: Delicious Food Delivery

springdoc:
  swagger-ui:
    path: /swagger
    tags-sorter: alpha
    operations-sorter: method
    groups-order: DESC
    doc-expansion: none
    default-model-expand-depth: 1
  api-docs:
    path: /api-docs